alter table OOP1_INDIVIDUAL add constraint FK_OOP1_INDIVIDUAL_ON_WORK_SHOP foreign key (WORK_SHOP_ID) references OOP1_WORK_SHOP(ID);
create index IDX_OOP1_INDIVIDUAL_ON_WORK_SHOP on OOP1_INDIVIDUAL (WORK_SHOP_ID);
